baseURL = "https://cloudinnovations.hk/"
title = "Cloud Innovations"
languageCode = "en-us"
theme = "airspace-hugo"

[params]
  googleAnalyticsID = "UA-XXXXXXXXX-X" # Replace with your actual GA ID
  description = "Cloud Innovations – IT Solutions Provider"
  author = "Cloud Innovations"
  logo = "img/logo.png"

[params.slider]
  enable = true
  title = "Empowering Your Business with Cloud Solutions"
  subtitle = "Innovative IT services tailored to your needs."
  bgImage = "img/hero-cloud.jpg"
  btnText = "Discover Our Services"
  url = "#services"

[params.wrapper]
  enable = true
  image = "img/about-cloud.jpg"
  title = "About Cloud Innovations"
  italic = "Leading IT solutions provider"
  paragraph = "Cloud Innovations helps businesses leverage cloud technology for growth and efficiency. Our solutions are designed to be simple, efficient, and scalable."

[params.contact]
  enable = true
  title = "Get in Touch"
  subtitle = "Contact us for a consultation or to learn more about our services."
  [params.contact.form]
    mail = "info@cloudinnovations.hk"
    name = "Your name"
    email = "Your email"
    subject = "Your subject"
    message = "Your message"
    button = "Send message"
  [params.contact.box]
    title = "Cloud Innovations"
    address = "Hong Kong"
    email = "info@cloudinnovations.hk"
    phone = "+852 XXXX XXXX"

[menu]
  [[menu.main]]
    weight = 1
    name = "Home"
    url = "/"
  [[menu.main]]
    weight = 2
    name = "Services"
    url = "/services"
  [[menu.main]]
    weight = 3
    name = "About"
    url = "/about"
  [[menu.main]]
    weight = 4
    name = "Portfolio"
    url = "/portfolio"
  [[menu.main]]
    weight = 5
    name = "Contact"
    url = "/contact"
