title = "Cloud Innovations"
logo = "logo.png"
baseURL = "https://cloudinnovations.hk/"
theme = "airspace-hugo"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

# The site's parameters
[params]
  # Google Analytics
  googleAnalitycsID = "UA-145017939-1"
  description = "Cloud Innovations - IT Solutions"
  author = "Cloud Innovations"

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

# Multilingual : SL / EN
[Languages]

  ######## english language
  [Languages.en]
    languageName = "En"
    weight = 2
    languageCode = "en-us"
    title = "Cloud Innovations"
    dateFormat = "January 2, 2006"
    home = "Home"

    [Languages.en.menu]
      #[[Languages.en.menu.header]]
      #  weight = 2
      #  name = "Team"
      #  url = "en/team"
      #[[Languages.en.menu.header]]
      #  weight = 8
      #  name = "Contact"
      #  url = "en/contact"

  # Add more languages as needed

[Languages.en.params.slider]
  enable = true
  title = "Cloud Innovations - Your IT Partner"
  subtitle = "Empowering your business with cloud and IT solutions"
  bgImage = "img/slider-bg.jpg"
  btnText = "Our Services and Expertise"
  url = "#service"

[Languages.en.params.wrapper]
  enable = true
  image = "img/kiss2.jpg"
  title = "The Cloud Innovations Story"
  italic = "Cloud Innovations is an IT solutions company based in Hong Kong. We specialize in cloud technologies, system integration, and digital transformation for businesses of all sizes."
  paragraph = "At Cloud Innovations, we believe technology should drive your business forward. Our solutions are designed to be simple, efficient, and scalable, helping you focus on what matters most."

[Languages.en.params.contact]
  enable = true
  title = "Drop us a note"
  subtitle = "Don’t just take our word for it. Check out some of our latest work."
  [Languages.en.params.contact.form]
    mail = "info@cloudinnovations.hk"
    name = "Your name"
    email = "Your email"
    subject = "Your subject"
    message = "Your message"
    button = "Send message"
  [Languages.en.params.contact.box]
    title = "Cloud Innovations"
    address = "Hong Kong"
    email = "info@cloudinnovations.hk"
    phone = "Phone: +852 XXXX XXXX"

        
      [[Languages.fr.params.contact.social]]
        icon = "fa-github"
        link = "#"

      [Languages.fr.params.contact.gmaps]
        title = "We Also Count in Google Maps"
